### ISSUE TITLE
API Error misleading

### ISSUE THREAD

**Issue by travismolick** [jkwill87/mnamer#101]
I am getting this crash report

`============================== CRASH REPORT BEGIN ==============================

--------------------------------- environment ----------------------------------

 - date = 2020-09-19
 - platform = Linux-5.4.48-06434-gd868196d13af-x86_64-with-debian-10.5
 - arguments = ['--media', 'movie', '--hits', '7', '--movie-directory', './', './']
 - python version = 3.7.3
 - mnamer version = 2.4.1
 - requests cache = /home/USERNAME/.cache/mnamer-py3.7.sql

--------------------------------- stack trace ----------------------------------

Traceback (most recent call last):
  File "/home/USERNAME/.local/lib/python3.7/site-packages/mnamer/\_\_main\_\_.py", line 23, in main
    frontend.launch()
  File "/home/USERNAME/.local/lib/python3.7/site-packages/mnamer/frontends.py", line 80, in launch
    self._process_targets()
  File "/home/USERNAME/.local/lib/python3.7/site-packages/mnamer/frontends.py", line 97, in _process_targets
    matches = target.query()
  File "/home/USERNAME/.local/lib/python3.7/site-packages/mnamer/target.py", line 221, in query
    for idx, result in enumerate(results, start=1):
  File "/home/USERNAME/.local/lib/python3.7/site-packages/mnamer/providers.py", line 79, in search
    yield from results
  File "/home/USERNAME/.local/lib/python3.7/site-packages/mnamer/providers.py", line 120, in _search_movie
    cache=self.cache,
  File "/home/USERNAME/.local/lib/python3.7/site-packages/mnamer/endpoints.py", line 111, in omdb_search
    raise MnamerException("invalid API key")
mnamer.exceptions.MnamerException: invalid API key

=============================== CRASH REPORT END ===============================`

I can see it says "invalid API key" for omdb but the key is valid, I have just reached the API limit for the day, would it be possible to have it display a different error code?

This is the code that comes back via https://www.omdbapi.com/?apikey=APIKEY after hitting a limit

`{"Response":"False","Error":"Request limit reached!"}`

I am hoping this helps for a fix or more info

**Comment by zendamacf** [comment]
Looks like this is a bug with OMDb unfortunately:
https://github.com/omdbapi/OMDb-API/issues/55
