### ISSUE TITLE
Docker : Crash while changing user

### ISSUE THREAD

**Issue by waenhill** [jkwill87/mnamer#102]
Hello,
First of all thats for your your on that awesome tool.

I have been using it through Docker container on linux system (Debian). It is working fine except that it is creating folders with "root" user.
I have tried to use the option `--user="1001:1001"`, but it didn't worked and gave the below crash report.
And I wasn't able to find any environment parameter that could help to change the user/group.

Here is the command used to run the container:
`docker run --rm --volume="/mnamer:/config"  --volume="/Medias:/mnt" --user="1001:1001" jkwill87/mnamer:latest --batch --recurse --config-path="/config/.mnamer-v2.json" /mnt/Movie.2007.720p`

Could you please help me with that? Is there any other way to avoid the 'root' user?
Thanks a lot in advance!

```
============================== CRASH REPORT BEGIN ==============================

--------------------------------- environment ----------------------------------

 - date = 2020-09-22
 - platform = Linux-4.19.0-8-amd64-x86_64-with
 - arguments = ['--config-path=/config/.mnamer-v2.json', '--batch', '--recurse', '/mnt/Movie.2007.720p']
 - python version = 3.8.3
 - mnamer version = 2.4.1
 - requests cache = /.cache/mnamer-py3.8.sql

--------------------------------- stack trace ----------------------------------

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/mnamer/__main__.py", line 23, in main
    frontend.launch()
  File "/usr/local/lib/python3.8/site-packages/mnamer/frontends.py", line 80, in launch
    self._process_targets()
  File "/usr/local/lib/python3.8/site-packages/mnamer/frontends.py", line 97, in _process_targets
    matches = target.query()
  File "/usr/local/lib/python3.8/site-packages/mnamer/target.py", line 221, in query
    for idx, result in enumerate(results, start=1):
  File "/usr/local/lib/python3.8/site-packages/mnamer/providers.py", line 156, in search
    yield from results
  File "/usr/local/lib/python3.8/site-packages/mnamer/providers.py", line 179, in _search_name
    response = tmdb_search_movies(
  File "/usr/local/lib/python3.8/site-packages/mnamer/endpoints.py", line 216, in tmdb_search_movies
    status, content = request_json(url, parameters, cache=cache)
  File "/usr/local/lib/python3.8/site-packages/mnamer/utils.py", line 259, in request_json
    session = get_session()
  File "/usr/local/lib/python3.8/site-packages/mnamer/utils.py", line 183, in get_session
    get_session.session = requests_cache.CachedSession(
  File "/usr/local/lib/python3.8/site-packages/requests_cache/core.py", line 73, in __init__
    self.cache = backends.create_backend(backend, cache_name, backend_options)
  File "/usr/local/lib/python3.8/site-packages/requests_cache/backends/__init__.py", line 63, in create_backend
    return registry[backend_name](cache_name, **options)
  File "/usr/local/lib/python3.8/site-packages/requests_cache/backends/sqlite.py", line 28, in __init__
    self.responses = DbPickleDict(location + extension, 'responses', fast_save=fast_save)
  File "/usr/local/lib/python3.8/site-packages/requests_cache/backends/storage/dbdict.py", line 62, in __init__
    with self.connection() as con:
  File "/usr/local/lib/python3.8/contextlib.py", line 113, in __enter__
    return next(self.gen)
  File "/usr/local/lib/python3.8/site-packages/requests_cache/backends/storage/dbdict.py", line 74, in connection
    con = sqlite.connect(self.filename)
sqlite3.OperationalError: unable to open database file

=============================== CRASH REPORT END ===============================
```

**Comment by waenhill** [comment]
Here is the command used to run the container:
`docker run --rm --volume="/mnamer:/config"  --volume="/Medias:/mnt" --user="1001:1001" jkwill87/mnamer:latest --batch --recurse --config-path="/config/.mnamer-v2.json" /mnt/Films/`

**Comment by jkwill87** [comment]
Updated the Dockerfile in [v2.4.2](https://github.com/jkwill87/mnamer/packages/303712). By default it will use 1000 for the UID and GID (the first non-root user and group for most systems). This can be overridden though using `UID` and `GID` build arg flags, however. Hopefully that works better for you, let me know if you have any issues.

**Comment by waenhill** [comment]
Hello,
Thanks a lot for your answer.
However it was not working for me as I am using GID different form UID. I did some changes in my local Dockerfile and finaly get it to work. I have proposed these changes in the pull request https://github.com/jkwill87/mnamer/pull/105
Could you please have a look and let me know if it is ok for you?
Please feel free to modify it :)
Thanks!
