### ISSUE TITLE
Some Type of Convert Error

### ISSUE THREAD

**Issue by jojobrogess** [jkwill87/mnamer#103]
hey i got an error. looks like I got sometype of country code error. can someone help me out?

--------------------------------- stack trace ----------------------------------

Traceback (most recent call last):
  File "/home/pi/.local/lib/python3.7/site-packages/babelfish/converters/__init__.py", line 157, in convert
    return self.to_symbol[alpha3]
KeyError: 'mul'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/pi/.local/lib/python3.7/site-packages/mnamer/__main__.py", line 22, in main
    frontend = Cli(settings)
  File "/home/pi/.local/lib/python3.7/site-packages/mnamer/frontends.py", line 67, in __init__
    super().__init__(settings)
  File "/home/pi/.local/lib/python3.7/site-packages/mnamer/frontends.py", line 25, in __init__
    self.targets = Target.populate_paths(self.settings)
  File "/home/pi/.local/lib/python3.7/site-packages/mnamer/target.py", line 61, in populate_paths
    targets = [cls(file_path, settings) for file_path in file_paths]
  File "/home/pi/.local/lib/python3.7/site-packages/mnamer/target.py", line 61, in <listcomp>
    targets = [cls(file_path, settings) for file_path in file_paths]
  File "/home/pi/.local/lib/python3.7/site-packages/mnamer/target.py", line 47, in __init__
    self._parse(file_path)
  File "/home/pi/.local/lib/python3.7/site-packages/mnamer/target.py", line 122, in _parse
    path_data[k] = Language.parse(v)
  File "/home/pi/.local/lib/python3.7/site-packages/mnamer/language.py", line 48, in parse
    return cls(value.name, value.alpha2, value.alpha3)
  File "/home/pi/.local/lib/python3.7/site-packages/babelfish/language.py", line 150, in __getattr__
    return language_converters[name].convert(alpha3, country, script)
  File "/home/pi/.local/lib/python3.7/site-packages/babelfish/converters/__init__.py", line 159, in convert
    raise LanguageConvertError(alpha3, country, script)
babelfish.exceptions.LanguageConvertError: mul

=============================== CRASH REPORT END ===============================

**Comment by waenhill** [comment]
Hello,
Maybe it would be better if you provide the full crash report, including the **environment** part...

I actualy got the same issue with file having `MULTi` in its name.
So as you suggested it seems that mnamer is trying to match the language with that label, and it does not exists.

Until a fix is found; and if you want to get unblock, you have to remove what looks like that `MULTi`, `MUL`, and so on.
It worked in my case, could you try from your side?
Thanks

**Comment by jkwill87** [comment]
@jojobrogess please include the full crash report, I need to know the file path to reproduce and fix the issue

**Comment by jojobrogess** [comment]
Sorry, working like crazy. I was using the -br parameters for a lot of files (100+) when I first ran into it and started yanking files out of the directory until the script ran clean in test mode, so I could figure out what file was causing the error. The file has 3 subtitles in it, so maybe I didn't set something up correctly? 
I could be wrong though, I'm little out of my league here to be honest.
I like this software and thought I'd share if there was an actual problem. 
Thanks for your quick reply! 
btw I'm running it on a rpi 4 using the latest firmware in a bash inotifywait scenario, if that helps. 

============================== CRASH REPORT BEGIN ==============================

--------------------------------- environment ----------------------------------

 - date = 2020-09-25
 - platform = Linux-5.4.51-v7l+-armv7l-with-debian-10.4
 - arguments = ['-br', '/home/pi/Desktop/DeleteTV/finish.txt', '/home/pi/Desktop/DeleteTV/Romeo + Juliet (BDrip 1080p ENG-ITA-FRA-GER - Aac) Multisub x264 bluray (1996)']
 - python version = 3.7.3
 - mnamer version = 2.4.1
 - requests cache = /home/pi/.cache/mnamer-py3.7.sql

--------------------------------- stack trace ----------------------------------

Traceback (most recent call last):
  File "/home/pi/.local/lib/python3.7/site-packages/babelfish/converters/__init__.py", line 157, in convert
    return self.to_symbol[alpha3]
KeyError: 'mul'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/pi/.local/lib/python3.7/site-packages/mnamer/__main__.py", line 22, in main
    frontend = Cli(settings)
  File "/home/pi/.local/lib/python3.7/site-packages/mnamer/frontends.py", line 67, in __init__
    super().__init__(settings)
  File "/home/pi/.local/lib/python3.7/site-packages/mnamer/frontends.py", line 25, in __init__
    self.targets = Target.populate_paths(self.settings)
  File "/home/pi/.local/lib/python3.7/site-packages/mnamer/target.py", line 61, in populate_paths
    targets = [cls(file_path, settings) for file_path in file_paths]
  File "/home/pi/.local/lib/python3.7/site-packages/mnamer/target.py", line 61, in <listcomp>
    targets = [cls(file_path, settings) for file_path in file_paths]
  File "/home/pi/.local/lib/python3.7/site-packages/mnamer/target.py", line 47, in __init__
    self._parse(file_path)
  File "/home/pi/.local/lib/python3.7/site-packages/mnamer/target.py", line 122, in _parse
    path_data[k] = Language.parse(v)
  File "/home/pi/.local/lib/python3.7/site-packages/mnamer/language.py", line 48, in parse
    return cls(value.name, value.alpha2, value.alpha3)
  File "/home/pi/.local/lib/python3.7/site-packages/babelfish/language.py", line 150, in __getattr__
    return language_converters[name].convert(alpha3, country, script)
  File "/home/pi/.local/lib/python3.7/site-packages/babelfish/converters/__init__.py", line 159, in convert
    raise LanguageConvertError(alpha3, country, script)
babelfish.exceptions.LanguageConvertError: mul

=============================== CRASH REPORT END ===============================

**Comment by meinnamehier** [comment]
This seems to be the same problem as https://github.com/jkwill87/mnamer/issues/95
I encountered the same problem, and I have no files with "mul" in the name.
