### ISSUE TITLE
[ArchLinux] Seems to be not working after with python-guessit 3.2.0 (rebulk 3.0.1)

### ISSUE THREAD

**Issue by nacho-domatix** [jkwill87/mnamer#117]
```	
$ mnamer
Traceback (most recent call last):
  File "/usr/bin/mnamer", line 33, in <module>
    sys.exit(load_entry_point('mnamer==2.4.2', 'console_scripts', 'mnamer')())
  File "/usr/bin/mnamer", line 22, in importlib_load_entry_point
    for entry_point in distribution(dist_name).entry_points
  File "/usr/lib/python3.9/importlib/metadata.py", line 524, in distribution
    return Distribution.from_name(distribution_name)
  File "/usr/lib/python3.9/importlib/metadata.py", line 187, in from_name
```

**Comment by jkwill87** [comment]
<img width="1268" alt="image" src="https://user-images.githubusercontent.com/4343678/103732816-3ebabe00-4fb6-11eb-9bc2-90c1b8a61dde.png">

guessit 3.2 / rebulk 3.0.1 seems to working for me locally. If you can post the result of `pip3 freeze` and your error report I'd be happy to look into the issue further though.

Either way, the latest release pins `guessit==3.1.*`. I'm not the maintainer of the AUR package so installing it using pacman or running against system python is not supported. It is recommend installing mnamer using `pip3 --user` or `pipx` which will ensure the proper versions and prevent incompatibilities with other Python packages.

**Comment by jkwill87** [comment]
After further investigation this may be due to pacman's recent update from Python 3.8 to Python 3.9. Other AUR Python packages have reported similar breakages elsewhere on the internet. I suspect that you may some dependencies installed with Python 3.9 and other from the AUR using Python 3.8 if you installed it using the AUR. If this is the case perhaps uninstalling and reinstalling the following packages will resolve the issue:

```
python-appdirs (python-appdirs-git)
python-dataclasses
python-guessit
python-requests
python-requests-cache
python-teletype
python-setuptools (make)
```

**Comment by nacho-domatix** [comment]
Thanks for the response! 

I reinstalled everything (tried to remove all the packages but some of them are dependencies already of the system). I couldn't make it work with AUR, but what's weird, in my laptop, with pretty much the same system/configuration as the desktop it's working fine. Anyway, the pip output is:

```
$ pip3 freeze
alabaster==0.7.12
apipkg==1.5
apparmor==3.0.1
appdirs==1.4.4
application-utility==1.3.2
argcomplete==1.12.1
argon2-cffi==20.1.0
asn1crypto==1.4.0
atomicwrites==1.4.0
attrs==20.3.0
Babel==2.9.0
babelfish==0.5.5
bcrypt==3.2.0
Beaker==1.11.0
beautifulsoup4==4.9.3
Brlapi==0.8.0
bsddb3==6.2.7
btrfsutil==5.9
CacheControl==0.12.6
cachetools==4.2.0
cffi==1.14.4
chardet==3.0.4
chrome-gnome-shell==0.0.0
colorama==0.4.4
commonmark==0.9.1
construct==2.10.56
contextlib2==0.6.0.post1
cryptography==3.3.1
cupshelpers==1.0
cycler==0.10.0
dataclasses==0.8
distlib==0.3.1
distro==1.5.0
docutils==0.16
duplicity==0.8.16
extras==1.0.0
fasteners==0.15
fixtures==3.0.0
future==0.18.2
gestures==0.2.3
google-api-core==1.24.1
google-api-python-client==1.12.8
google-auth==1.24.0
google-auth-httplib2==0.0.4
googleapis-common-protos==1.52.0
guessit==3.2.0
gufw==20.4.0
html2text==2020.1.16
html5lib==1.1
httplib2==0.18.1
idna==2.10
imagesize==1.2.0
img2pdf==0.4.0
importlib-metadata==3.3.0
iniconfig==1.1.1
inotify==0.2.10
isc==2.0
Jade-Application-Kit==3.5.6
Jinja2==2.11.2
kiwisolver==1.3.1
langdetect==1.0.8
layoutswitcherlib==0.8.16
lensfun==0.3.95
LibAppArmor==3.0.1
libfdt==1.6.0
lockfile==0.12.2
louis==3.16.0
lxml==4.6.2
Mako==1.1.3
Markdown==3.3.3
MarkupSafe==1.1.1
matplotlib==3.3.3
meson==0.56.0
mnamer==2.4.2
monotonic==1.5
more-itertools==8.6.0
mox3==1.1.0
msgpack==1.0.2
mutagen==1.45.1
netsnmp-python==1.0a1
nose==1.3.7
npyscreen==4.10.5
numpy==1.19.4
oauth2client==4.1.3
ordered-set==4.0.2
packaging==20.8
pacman-mirrors==4.19.1
paramiko==2.7.2
pbr==5.5.1
pdfarranger==1.6.2
pep517==0.9.1
pikepdf==2.2.2
Pillow==8.0.1
pluggy==0.13.1
ply==3.11
progress==1.5
progressbar2==3.53.1
protobuf==3.12.4
pwquality==1.4.4
py==1.10.0
pyasn1==0.4.8
pyasn1-modules==0.2.8
pycairo==1.20.0
pycparser==2.20
pycryptodome==3.9.9
pycryptodomex==3.9.9
pycups==2.0.1
pycurl==7.43.0.6
PyDrive==1.3.1
pyenchant==3.1.1
pygame==2.0.0
Pygments==2.7.3
PyGObject==3.38.0
pyinotify==0.9.6
pykeepass==3.2.1
pylast==4.0.0
pymediainfo==5.0.3
PyNaCl==1.4.0
PyOpenGL==3.1.5
pyOpenSSL==20.0.1
pypandoc==1.5
pyparsing==2.4.7
PyPDF2==1.26.0
PyQt5==5.15.2
PyQt5-sip==12.8.1
PyQtWebEngine==5.15.2
pyrsistent==0.17.3
pysmbc==1.0.23
pytest==6.2.1
python-dateutil==2.8.1
python-distutils-extra==2.39
python-Levenshtein==0.12.0
python-mimeparse==1.6.0
python-utils==2.4.0
pytoml==0.1.21
pytz==2020.5
pyudev==0.22.0.dev20201112
pyxdg==0.26
PyYAML==5.3.1
rebulk==3.0.1
regex==2020.11.13
reportlab==3.5.57
requests==2.25.1
requests-cache==0.5.2
resolvelib==0.5.4
retrying==1.3.3
rsa==4.6
setproctitle==1.2.1
simplejson==3.17.2
sip==4.19.24
six==1.15.0
snowballstemmer==2.0.0
solaar==1.0.4
soupsieve==2.1
Sphinx==3.4.1
sphinxcontrib-applehelp==1.0.2
sphinxcontrib-devhelp==1.0.2
sphinxcontrib-htmlhelp==1.0.3
sphinxcontrib-jsmath==1.0.1
sphinxcontrib-qthelp==1.0.3
sphinxcontrib-serializinghtml==1.1.4
subtitle==2.1
team==1.0
teletype==1.1.0
testtools==2.4.0
toml==0.10.2
ufw==0.36
uritemplate==3.0.1
urllib3==1.26.1
wcwidth==0.2.5
webencodings==0.5.1
websocket-client==0.57.0
xmltodict==0.12.0
youtube-dl==2020.12.31
yq==2.11.1
zipp==3.4.0
```

And installing it using `pip3 mnamer` made it work inmediatly :)

**Comment by hubnerd** [comment]
I believe this is due to guessit dependency needing to be version 3.1.* in requirements.txt, latest guessit has been updated to 3.2 in aur. Building locally works when requirements.txt is changed to use guessit 3.2.* instead.

**Comment by jkwill87** [comment]
Thanks for follow up. I'll bump the guessit version, publish a new release, then ping the AUR maintainer to update. Hopefully that should sort out the issue for Arch folks 🙂

**Comment by TheFrenchGhosty** [comment]
mnamer works perfectly on Arch. I can confirm that python 3.9 broke a ton of packages (they need to be reinstalled to work again, I for example had to reinstall python-babelfish  and python-requests-cache  otherwise mnamer complained.

@jkwill87 I really would like to thank you again for making this, this is trully a fantastic tool, that I use so much!
