### ISSUE TITLE
Crash on standard filenames

### ISSUE THREAD

**Issue by AndrewAPAC** [jkwill87/mnamer#132]
Hi 

Seeing a crash on the following filenames:

* `Get.Smart.-.1x27.-.Ship.Of.Spies.pt1.avi`
* `Get.Smart.-.1x28.-.Ship.Of.Spies.pt2.avi`

`thetvdb.com` has parentheses in the names and I think this is the problem.  Additionally, I am replacing '(' with an empty string in my mnamer config (below crash report).  Without this replacement it is OK.

Thanks for your work on this - I am using it to replace the use of filebot now it is closed source and being charged for.

Crash report

```
============================== CRASH REPORT BEGIN ==============================

--------------------------------- environment ----------------------------------

 - date = 2021-03-29
 - platform = Darwin-19.6.0-x86_64-i386-64bit
 - arguments = ['Get.Smart.-.1x28.-.Ship.Of.Spies.pt2.avi']
 - cache location = /Users/andrew/Library/Caches/mnamer-py3.7.sql
 - python version = 3.7.5
 - mnamer version = 2.5.2
 - appdirs version = 1.4.4
 - babelfish version = 0.5.5-dev
 - guessit version = 3.2.0
 - requests version = 2.24.0
 - requests cache version = 0.5.2
 - teletype version = 1.1.0

--------------------------------- stack trace ----------------------------------

Traceback (most recent call last):
  File "/usr/local/share/python/py37/lib/python3.7/site-packages/mnamer/__main__.py", line 23, in main
    frontend.launch()
  File "/usr/local/share/python/py37/lib/python3.7/site-packages/mnamer/frontends.py", line 80, in launch
    self._process_targets()
  File "/usr/local/share/python/py37/lib/python3.7/site-packages/mnamer/frontends.py", line 140, in _process_targets
    if target.destination == target.source:
  File "/usr/local/share/python/py37/lib/python3.7/site-packages/mnamer/target.py", line 106, in destination
    filename = filename_replace(filename, self._settings.replace_after)
  File "/usr/local/share/python/py37/lib/python3.7/site-packages/mnamer/utils.py", line 108, in filename_replace
    base = str_replace(base, replacements)
  File "/usr/local/share/python/py37/lib/python3.7/site-packages/mnamer/utils.py", line 328, in str_replace
    s = re.sub(word, replacement, s, flags=re.IGNORECASE)
  File "/Users/andrew/.conda/envs/py37/lib/python3.7/re.py", line 192, in sub
    return _compile(pattern, flags).sub(repl, string, count)
  File "/Users/andrew/.conda/envs/py37/lib/python3.7/re.py", line 286, in _compile
    p = sre_compile.compile(pattern, flags)
  File "/Users/andrew/.conda/envs/py37/lib/python3.7/sre_compile.py", line 764, in compile
    p = sre_parse.parse(p, flags)
  File "/Users/andrew/.conda/envs/py37/lib/python3.7/sre_parse.py", line 924, in parse
    p = _parse_sub(source, pattern, flags & SRE_FLAG_VERBOSE, 0)
  File "/Users/andrew/.conda/envs/py37/lib/python3.7/sre_parse.py", line 420, in _parse_sub
    not nested and not items))
  File "/Users/andrew/.conda/envs/py37/lib/python3.7/sre_parse.py", line 813, in _parse
    source.tell() - start)
re.error: missing ), unterminated subpattern at position 0

=============================== CRASH REPORT END ===============================
```

`~/.mnamer-v2.json`
```
andrew@cass-imac:.../Get.Smart/Season.01$ cat ~/.mnamer-v2.json                 {
    "api_key_omdb": null,
    "api_key_tmdb": null,
    "api_key_tvdb": null,
    "api_key_tvmaze": null,
    "batch": true,
    "episode_api": "tvdb",
    "episode_directory": null,
    "episode_format": "S{season:02}E{episode:02}.{title}.{extension}",
    "hits": 5,
    "ignore": [
        ".*sample.*",
        "^RARBG.*"
    ],
    "lower": false,
    "mask": [
        ".avi",
        ".m4v",
        ".mp4",
        ".mkv",
        ".ts",
        ".wmv",
        ".srt",
        ".idx",
        ".sub"
    ],
    "movie_api": "tmdb",
    "movie_directory": null,
    "movie_format": "{name}.{extension}",
    "no_guess": true,
    "no_overwrite": true,
    "no_style": false,
    "recurse": false,
    "replace_after": {
        "&": "and",
        ";": ".",
        "@": "at",
        "[": "",
        "]": "",
        "(": "",
        ")": "",
        "'": "",
        "?": "",
        "!": "",
        ",": ".",
        ":": ".",
        "\"": ".",
        " ": "."
    },
    "replace_before": {},
    "scene": false,
    "verbose": false
}
```

**Comment by AndrewAPAC** [comment]
This one also crashed: `Get.Smart.-.2x23.-.Where-What-How-Who.Am.I.avi`.  Seems to be the substitution of the '?'

**Comment by AndrewAPAC** [comment]
I've created a fix for this but do not have permission to push to a new branch.  The fix is very simple and you can use this patch if you don't want to allow me to create a branch in the repo.

```
--- a/mnamer/utils.py
+++ b/mnamer/utils.py
@@ -325,6 +325,8 @@ def str_replace(s: str, replacements: Dict[str, str]) -> str:
     """Replaces keys in replacements dict with their values."""
     for word, replacement in replacements.items():
         if word in s:
+            if word in (['(', ')', '[', ']', '+', '?', '*']):
+                word = '\\' + word
             s = re.sub(word, replacement, s, flags=re.IGNORECASE)
     return s
```

**Comment by jkwill87** [comment]
Thanks, will give this a look later tonight 👀

**Comment by AnalogMan151** [comment]
You just need to change this one line:
 ```
 --- a/mnamer/utils.py
 +++ b/mnamer/utils.py
 @@ -325,6 +325,8 @@ def str_replace(s: str, replacements: Dict[str, str]) -> str:
      """Replaces keys in replacements dict with their values."""
      for word, replacement in replacements.items():
          if word in s:
-             s = re.sub(word, replacement, s, flags=re.IGNORECASE)
+             s = re.sub(re.escape(word), replacement, s, flags=re.IGNORECASE)
      return s
 ```

**Comment by AndrewAPAC** [comment]
Even better!
