### ISSUE TITLE
Crashes

### ISSUE THREAD

**Issue by BitBlockv6** [jkwill87/mnamer#149]
(venv) root@OpenWrt:/git/mnamer# /git/mnamer/venv/bin//mnamer "/sdb1/Entpackt" --config-path=/etc/mnamer-v2.json

============================== CRASH REPORT BEGIN ==============================

--------------------------------- environment ----------------------------------

 - date = 2021-06-12
 - platform = Linux-4.14.221-armv7l-with-libc
 - arguments = ['/sdb1/Entpackt', '--config-path=/etc/mnamer-v2.json']
 - cache location = /root/.cache/mnamer-py3.7.sql
 - python version = 3.7.10
 - mnamer version = 2.5.3
 - appdirs version = 1.4.4
 - babelfish version = 0.5.5-dev
 - guessit version = 3.2.0
 - requests version = 2.25.1
 - requests cache version = 0.5.2
 - teletype version = 1.1.0

--------------------------------- stack trace ----------------------------------

Traceback (most recent call last):
  File "/git/mnamer/venv/lib/python3.7/site-packages/mnamer/__main__.py", line 22, in main
    frontend = Cli(settings)
  File "/git/mnamer/venv/lib/python3.7/site-packages/mnamer/frontends.py", line 67, in __init__
    super().__init__(settings)
  File "/git/mnamer/venv/lib/python3.7/site-packages/mnamer/frontends.py", line 25, in __init__
    self.targets = Target.populate_paths(self.settings)
  File "/git/mnamer/venv/lib/python3.7/site-packages/mnamer/target.py", line 60, in populate_paths
    file_paths = filter_blacklist(file_paths, settings.ignore)
  File "/git/mnamer/venv/lib/python3.7/site-packages/mnamer/utils.py", line 116, in filter_blacklist
    for path in paths
  File "/git/mnamer/venv/lib/python3.7/site-packages/mnamer/utils.py", line 119, in <listcomp>
    for pattern in blacklist
  File "/git/mnamer/venv/lib/python3.7/site-packages/mnamer/utils.py", line 120, in <genexpr>
    if pattern
  File "/usr/lib/python3.7/re.py", line 185, in search
    return _compile(pattern, flags).search(string)
  File "/usr/lib/python3.7/re.py", line 288, in _compile
    p = sre_compile.compile(pattern, flags)
  File "/usr/lib/python3.7/sre_compile.py", line 764, in compile
    p = sre_parse.parse(p, flags)
  File "/usr/lib/python3.7/sre_parse.py", line 924, in parse
    p = _parse_sub(source, pattern, flags & SRE_FLAG_VERBOSE, 0)
  File "/usr/lib/python3.7/sre_parse.py", line 420, in _parse_sub
    not nested and not items))
  File "/usr/lib/python3.7/sre_parse.py", line 645, in _parse
    source.tell() - here + len(this))
re.error: nothing to repeat at position 0

=============================== CRASH REPORT END ===============================

requirements installed from the requirements.txt with virtualenv.  
Same Error without virtualenv and installed with "pip3 install mnamer"
Dont know how to solve this! before it runs perfect ...

**Comment by jkwill87** [comment]
Looks like mnamer is having problems parsing your `ignore` settings. Do you have any custom ones set in `/etc/mnamer-v2.json`?

**Comment by BitBlockv6** [comment]
Thanks! There was a problem in the ignore list. Works perfect again.
