### ISSUE TITLE
Unable to use python requests cache >= 6.0 due to use of _is_cache_disabled

### ISSUE THREAD

**Issue by hubnerd** [jkwill87/mnamer#168]
Hi,

If trying to use the dependency "requests cache" that equals or is over 6.0 you get the following:

Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/mnamer/__main__.py", line 23, in main
    frontend.launch()
  File "/usr/lib/python3.9/site-packages/mnamer/frontends.py", line 80, in launch
    self._process_targets()
  File "/usr/lib/python3.9/site-packages/mnamer/frontends.py", line 97, in _process_targets
    matches = target.query()
  File "/usr/lib/python3.9/site-packages/mnamer/target.py", line 233, in query
    for idx, result in enumerate(results, start=1):
  File "/usr/lib/python3.9/site-packages/mnamer/providers.py", line 374, in search
    yield from self._search_with_season_and_episode(
  File "/usr/lib/python3.9/site-packages/mnamer/providers.py", line 437, in _search_with_season_and_episode
    series_data = tvmaze_show_search(series)
  File "/usr/lib/python3.9/site-packages/mnamer/endpoints.py", line 466, in tvmaze_show_search
    status, content = request_json(url, parameters, cache=cache)
  File "/usr/lib/python3.9/site-packages/mnamer/utils.py", line 283, in request_json
    initial_cache_state = session._is_cache_disabled  # yes, i'm a bad person
AttributeError: 'CachedSession' object has no attribute '_is_cache_disabled'

I seems you were indeed a bad person :)

Thanks

**Comment by jkwill87** [comment]
Should be fixed in c8bbc63, will put up a new release after some more testing.

**Comment by volker-fr** [comment]
There seems to be no new release after this fix. Neither on github, nor on pypi.org
