### ISSUE TITLE
bad escape (end of pattern) at position 0

### ISSUE THREAD

**Issue by zrahman001** [jkwill87/mnamer#169]
Processing Episode "Squid.Game.S01E06.mkv" (450.04MB)

============================== CRASH REPORT BEGIN ==============================

--------------------------------- environment ----------------------------------

 - date = 2021-11-09
 - platform = Linux-4.15.0-158-generic-x86_64-with-Ubuntu-18.04-bionic
 - arguments = ['Squid.Game.S01E06.mkv']
 - cache location = /home/zrahman/.cache/mnamer-py3.6.sql
 - python version = 3.6.9
 - mnamer version = 2.5.2
 - appdirs version = 1.4.4
 - babelfish version = 0.5.5-dev
 - guessit version = 3.2.0
 - requests version = 2.25.1
 - requests cache version = 0.5.2
 - teletype version = 1.1.0

--------------------------------- stack trace ----------------------------------

Traceback (most recent call last):
  File "/home/zrahman/.local/lib/python3.6/site-packages/mnamer/__main__.py", line 23, in main
    frontend.launch()
  File "/home/zrahman/.local/lib/python3.6/site-packages/mnamer/frontends.py", line 80, in launch
    self._process_targets()
  File "/home/zrahman/.local/lib/python3.6/site-packages/mnamer/frontends.py", line 97, in _process_targets
    matches = target.query()
  File "/home/zrahman/.local/lib/python3.6/site-packages/mnamer/target.py", line 233, in query
    for idx, result in enumerate(results, start=1):
  File "/home/zrahman/.local/lib/python3.6/site-packages/mnamer/providers.py", line 245, in search
    for result in results:
  File "/home/zrahman/.local/lib/python3.6/site-packages/mnamer/providers.py", line 309, in _search_series
    series_id, season, episode, language
  File "/home/zrahman/.local/lib/python3.6/site-packages/mnamer/providers.py", line 283, in _search_id
    title=entry["episodeName"].split(";", 1)[0],
  File "<string>", line 13, in __init__
  File "/home/zrahman/.local/lib/python3.6/site-packages/mnamer/metadata.py", line 160, in __setattr__
    value = converter(value)
  File "/home/zrahman/.local/lib/python3.6/site-packages/mnamer/utils.py", line 155, in resolver
    x = fn(x)
  File "/home/zrahman/.local/lib/python3.6/site-packages/mnamer/utils.py", line 333, in str_replace_slashes
    return str_replace(s, {"/": "-", "\\": "-"})
  File "/home/zrahman/.local/lib/python3.6/site-packages/mnamer/utils.py", line 328, in str_replace
    s = re.sub(word, replacement, s, flags=re.IGNORECASE)
  File "/usr/lib/python3.6/re.py", line 191, in sub
    return _compile(pattern, flags).sub(repl, string, count)
  File "/usr/lib/python3.6/re.py", line 301, in _compile
    p = sre_compile.compile(pattern, flags)
  File "/usr/lib/python3.6/sre_compile.py", line 562, in compile
    p = sre_parse.parse(p, flags)
  File "/usr/lib/python3.6/sre_parse.py", line 847, in parse
    source = Tokenizer(str)
  File "/usr/lib/python3.6/sre_parse.py", line 231, in __init__
    self.__next()
  File "/usr/lib/python3.6/sre_parse.py", line 245, in __next
    self.string, len(self.string) - 1) from None
sre_constants.error: bad escape (end of pattern) at position 0

=============================== CRASH REPORT END ===============================

Dang, it looks like mnamer crashed! Please consider filling an issue at
https://github.com/jkwill87/mnamer/issues along with this report.

**Comment by ereinstein** [comment]
I am getting a similar crash report when running both `mnamer .` and `mnamer --test .` in a directory I want to use mnamer in.

```
--------------------------------- environment ----------------------------------

 - date = 2021-11-14
 - platform = Linux-5.15.2-zen1-1-zen-x86_64-with-glibc2.33
 - arguments = ['.']
 - cache location = /home/bruh/.cache/mnamer-py3.9.sql
 - python version = 3.9.7
 - mnamer version = 2.5.4
 - appdirs version = 1.4.4
 - guessit version = 3.4.2
 - requests version = 2.26.0
 - requests cache version = 0.8.1
 - teletype version = 1.1.0

--------------------------------- stack trace ----------------------------------

Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/mnamer/__main__.py", line 23, in main
    frontend.launch()
  File "/usr/lib/python3.9/site-packages/mnamer/frontends.py", line 80, in launch
    self._process_targets()
  File "/usr/lib/python3.9/site-packages/mnamer/frontends.py", line 97, in _process_targets
    matches = target.query()
  File "/usr/lib/python3.9/site-packages/mnamer/target.py", line 233, in query
    for idx, result in enumerate(results, start=1):
  File "/usr/lib/python3.9/site-packages/mnamer/providers.py", line 374, in search
    yield from self._search_with_season_and_episode(
  File "/usr/lib/python3.9/site-packages/mnamer/providers.py", line 437, in _search_with_season_and_episode
    series_data = tvmaze_show_search(series)
  File "/usr/lib/python3.9/site-packages/mnamer/endpoints.py", line 466, in tvmaze_show_search
    status, content = request_json(url, parameters, cache=cache)
  File "/usr/lib/python3.9/site-packages/mnamer/utils.py", line 283, in request_json
    initial_cache_state = session._is_cache_disabled  # yes, i'm a bad person
AttributeError: 'CachedSession' object has no attribute '_is_cache_disabled'
```
