### ISSUE TITLE
JSONDecodeError

### ISSUE THREAD

**Issue by Radiotechniman** [jkwill87/mnamer#201]
I receive the following error with everything I do
even "mnamer -V" generates the below

`Traceback (most recent call last):
  File "/home/niels/.local/bin/mnamer", line 8, in <module>
    sys.exit(main())
  File "/home/niels/.local/lib/python3.6/site-packages/mnamer/__main__.py", line 17, in main
    settings.load()
  File "/home/niels/.local/lib/python3.6/site-packages/mnamer/setting_store.py", line 427, in load
    config = json_loads(str(config_path)) if config_path else {}
  File "/home/niels/.local/lib/python3.6/site-packages/mnamer/utils.py", line 227, in json_loads
    return json.loads(json_data) if json_data else {}
  File "/usr/lib/python3.6/json/__init__.py", line 354, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.6/json/decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.6/json/decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 15 column 17 (char 454)
`

I thought i'd try the github version but that one cannot be installed due to unmet requirements:
ERROR: No matching distribution found for requests-cache~=0.9.7

**Comment by jkwill87** [comment]
This version of requests-cache only supports python 3.7+. The mnamer main branch only supports python 3.10+. Consider:

1. Upgrading system python.
2. Using pyenv to user install a more recent version of python.
3. Using the docker package.
4. Installing mnamer==2.5.2, which only requires requests-cache 0.5.* and supports python 3.6.
