### ISSUE TITLE
Crash on Arch Linux

### ISSUE THREAD

**Issue by ivovegter** [jkwill87/mnamer#302]
============================== CRASH REPORT BEGIN ==============================

--------------------------------- environment ----------------------------------

 - date = 2024-12-03
 - platform = Linux-6.12.1-arch1-1-x86_64-with-glibc2.40
 - arguments = ['-r', 'The Spanish Princess', 'The Tudors 2007 S01-S04 720p BluRay HEVC x265 BONE']
 - cache location = /home/captain/.cache/mnamer-py3.12.sqlite
 - python version = 3.12.7
 - mnamer version = 2.5.5
 - appdirs version = 1.4.4
 - guessit version = 3.8.0
 - requests version = 2.32.3
 - requests cache version = 1.2.1
 - teletype version = 1.3.4

--------------------------------- stack trace ----------------------------------

Traceback (most recent call last):
  File "/usr/lib/python3.12/site-packages/mnamer/__main__.py", line 23, in main
    frontend.launch()
  File "/usr/lib/python3.12/site-packages/mnamer/frontends.py", line 81, in launch
    self._process_targets()
  File "/usr/lib/python3.12/site-packages/mnamer/frontends.py", line 98, in _process_targets
    matches = target.query()
              ^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/mnamer/target.py", line 232, in query
    for idx, result in enumerate(results, start=1):
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/mnamer/providers.py", line 368, in search
    yield from self._search_with_season_and_episode(
  File "/usr/lib/python3.12/site-packages/mnamer/providers.py", line 433, in _search_with_season_and_episode
    series_data = tvmaze_show_search(series)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/mnamer/endpoints.py", line 435, in tvmaze_show_search
    status, content = request_json(url, parameters, cache=cache)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/mnamer/utils.py", line 259, in request_json
    initial_cache_state = session._disabled  # yes, i'm a bad person
                          ^^^^^^^^^^^^^^^^^
AttributeError: 'CachedSession' object has no attribute '_disabled'

=============================== CRASH REPORT END ===============================

**Comment by KL1RL** [comment]
`============================== CRASH REPORT BEGIN ==============================

--------------------------------- environment ----------------------------------

 - date = 2025-01-10
 - platform = Linux-6.12.4-arch1-1-x86_64-with-glibc2.40
 - arguments = ['censored_data_would_be_here']
 - cache location = /home/zorton/.cache/mnamer-py3.13.sqlite
 - python version = 3.13.1
 - mnamer version = 2.5.5
 - appdirs version = 1.4.4
 - guessit version = 3.8.0
 - requests version = 2.32.3
 - requests cache version = 1.2.1
 - teletype version = 1.3.4

--------------------------------- stack trace ----------------------------------

Traceback (most recent call last):
  File "/usr/lib/python3.13/site-packages/mnamer/__main__.py", line 23, in main
    frontend.launch()
    ~~~~~~~~~~~~~~~^^
  File "/usr/lib/python3.13/site-packages/mnamer/frontends.py", line 81, in launch
    self._process_targets()
    ~~~~~~~~~~~~~~~~~~~~~^^
  File "/usr/lib/python3.13/site-packages/mnamer/frontends.py", line 98, in _process_targets
    matches = target.query()
  File "/usr/lib/python3.13/site-packages/mnamer/target.py", line 232, in query
    for idx, result in enumerate(results, start=1):
                       ~~~~~~~~~^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.13/site-packages/mnamer/providers.py", line 368, in search
    yield from self._search_with_season_and_episode(
        query.series, query.season, query.episode
    )
  File "/usr/lib/python3.13/site-packages/mnamer/providers.py", line 433, in _search_with_season_and_episode
    series_data = tvmaze_show_search(series)
  File "/usr/lib/python3.13/site-packages/mnamer/endpoints.py", line 435, in tvmaze_show_search
    status, content = request_json(url, parameters, cache=cache)
                      ~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.13/site-packages/mnamer/utils.py", line 259, in request_json
    initial_cache_state = session._disabled  # yes, i'm a bad person
                          ^^^^^^^^^^^^^^^^^
AttributeError: 'CachedSession' object has no attribute '_disabled'

=============================== CRASH REPORT END ===============================`

Same for this system.....fix found:

changing all instances of "session._disabled" to "session.settings.disabled" in /usr/lib/python3.13/site-packages/mnamer/utils.py got it running again.  Likely a change in the python-requests-cache library.

**Comment by c4tz** [comment]
Hey, AUR pkg maintainer here. I just patched this in a new release. Hope @jkwill87 sees this and adds the patch to `mnamer` itself ;)

**Comment by jkwill87** [comment]
Should be resolved with current release 🤞
