### ISSUE TITLE
TypeError: must be str, not list on v2

### ISSUE THREAD

**Issue by fajulleiro** [jkwill87/mnamer#35]
I'm having problems with some of my videos when trying to rename them. It seems that mnamer doesn't like at all the name of the folder. One example:
` 
mnamer -V --movie_directory '/home/fajumon/share/kodi/movies_vos/' 'Toy Story 4 [MicroHD 1080p][AC3 5.1-DTS 5.1-Castellano-AC3 5.1 Ingles+Subs][ES-EN]/Toy Story IV.mkv'
Traceback (most recent call last):
  File "/home/fajumon/.pyenv/versions/mnamerdev/bin/mnamer", line 11, in <module>
    load_entry_point('mnamer==2.0.0', 'console_scripts', 'mnamer')()
  File "/home/fajumon/.pyenv/versions/3.6.9/envs/mnamerdev/lib/python3.6/site-packages/mnamer/__main__.py", line 25, in main
    targets = Target.populate_paths(args.targets, **config)
  File "/home/fajumon/.pyenv/versions/3.6.9/envs/mnamerdev/lib/python3.6/site-packages/mnamer/target.py", line 98, in populate_paths
    targets = {cls(path, **config) for path in paths}
  File "/home/fajumon/.pyenv/versions/3.6.9/envs/mnamerdev/lib/python3.6/site-packages/mnamer/target.py", line 98, in <setcomp>
    targets = {cls(path, **config) for path in paths}
  File "/home/fajumon/.pyenv/versions/3.6.9/envs/mnamerdev/lib/python3.6/site-packages/mnamer/target.py", line 35, in __init__
    self.metadata: Metadata = self.parse(path, config.get("media"))
  File "/home/fajumon/.pyenv/versions/3.6.9/envs/mnamerdev/lib/python3.6/site-packages/mnamer/target.py", line 166, in parse
    meta["quality"] += " " + data[field]
TypeError: must be str, not list
`
Maybe I need to change the name of the folder before using mnamer but ideally I'd hope the script would take care of it as is...
Any help would be appreciate. Thanks.

**Comment by jkwill87** [comment]
I'm looking to try and get mnamer v2 out this weekend. Hopefully, this will resolve the issue. Thanks!
