### ISSUE TITLE
mnamer crashes on recursive scan

### ISSUE THREAD

**Issue by BeardedIT** [jkwill87/mnamer#45]
============================== CRASH REPORT BEGIN ==============================

--------------------------------- environment ----------------------------------

 - date = 2020-02-03
 - platform = Linux-5.3.0-7625-generic-x86_64-with-Ubuntu-19.04-disco
 - arguments = ['-r', './']
 - python version = 3.7.3
 - mnamer version = 2.0.0

--------------------------------- stack trace ----------------------------------

Traceback (most recent call last):
  File "/home/karl/.local/lib/python3.7/site-packages/mnamer/__main__.py", line 32, in main
    run()
  File "/home/karl/.local/lib/python3.7/site-packages/mnamer/__main__.py", line 48, in run
    targets = Target.populate_paths(settings)
  File "/home/karl/.local/lib/python3.7/site-packages/mnamer/target.py", line 58, in populate_paths
    targets = [cls(file_path, settings) for file_path in file_paths]
  File "/home/karl/.local/lib/python3.7/site-packages/mnamer/target.py", line 58, in <listcomp>
    targets = [cls(file_path, settings) for file_path in file_paths]
  File "/home/karl/.local/lib/python3.7/site-packages/mnamer/target.py", line 43, in __init__
    file_path=file_path, media_hint=settings.media
  File "/home/karl/.local/lib/python3.7/site-packages/mnamer/metadata.py", line 214, in parse_metadata
    **dataclasses.asdict(metadata), file_path=file_path
  File "<string>", line 14, in __init__
  File "/home/karl/.local/lib/python3.7/site-packages/mnamer/metadata.py", line 172, in __post_init__
    self.episode = self._path_data.get("episode")
  File "/home/karl/.local/lib/python3.7/site-packages/mnamer/metadata.py", line 201, in __setattr__
    value = converter(value)
TypeError: int() argument must be a string, a bytes-like object or a number, not 'list'

**Comment by jkwill87** [comment]
Interesting. It doesn't seem like this is an issue with recurse per se but mnamer picking up a multi-part episode, something that doesn't seem accounted for. I'll look into fixing this, thanks!

**Comment by jkwill87** [comment]
Should be fixed in the latest version. Run`pip3 install -U mnamer` to update.
