### ISSUE TITLE
Crash report

### ISSUE THREAD

**Issue by barning** [jkwill87/mnamer#48]
============================== CRASH REPORT BEGIN ==============================

--------------------------------- environment ----------------------------------

 - date = 2020-02-12
 - platform = Darwin-19.3.0-x86_64-i386-64bit
 - arguments = ['Filme']
 - python version = 3.7.3
 - mnamer version = 2.1.0

--------------------------------- stack trace ----------------------------------

Traceback (most recent call last):
  File "/Library/Python/3.7/site-packages/mnamer/__main__.py", line 31, in main
    run()
  File "/Library/Python/3.7/site-packages/mnamer/__main__.py", line 109, in run
    matches = target.query()
  File "/Library/Python/3.7/site-packages/mnamer/target.py", line 147, in query
    for idx, result in enumerate(results, start=1):
  File "/Library/Python/3.7/site-packages/mnamer/providers.py", line 155, in search
    yield from results
  File "/Library/Python/3.7/site-packages/mnamer/providers.py", line 182, in _search_name
    year=entry["release_date"],
KeyError: 'release_date'

**Comment by zwgtdev** [comment]
Same error encountered. I'll fork and provide a PR

**Comment by jkwill87** [comment]
Should be fixed in v2.2.0.
