### ISSUE TITLE
Plus character in filename causes TypeError

### ISSUE THREAD

**Issue by colemar** [jkwill87/mnamer#86]
```
$ mnamer --version
mnamer v1.4.2

$ mnamer Dogman.2018.Bluray.Full.HD.1080p.x264.DTS+AC3.5.1.ITA.SUB-CB01HD.mkv

Starting mnamer

Detected File
Dogman.2018.Bluray.Full.HD.1080p.x264.DTS+AC3.5.1.ITA.SUB-CB01HD
Traceback (most recent call last):
  File "/usr/local/bin/mnamer", line 8, in <module>
    sys.exit(main())
  File "/home/admin/.local/lib/python3.5/site-packages/mnamer/__main__.py", line 385, in main
    process_files(targets, user_media, test_run, id_key, **config)
  File "/home/admin/.local/lib/python3.5/site-packages/mnamer/__main__.py", line 213, in process_files
    meta = meta_parse(file_path, user_media)
  File "/home/admin/.local/lib/python3.5/site-packages/mnamer/utils.py", line 200, in meta_parse
    meta["quality"] += " " + data[field]
TypeError: Can't convert 'list' object to str implicitly

$ mv Dogman.2018.Bluray.Full.HD.1080p.x264.DTS+AC3.5.1.ITA.SUB-CB01HD.mkv Dogman.2018.Bluray.Full.HD.1080p.x264.DTSAC3.5.1.ITA.SUB-CB01HD.mkv

$ mnamer Dogman.2018.Bluray.Full.HD.1080p.x264.DTSAC3.5.1.ITA.SUB-CB01HD.mkv

Starting mnamer

Detected File
Dogman.2018.Bluray.Full.HD.1080p.x264.DTSAC3.5.1.ITA.SUB-CB01HD

Query Results
  [1] Dogman (2018)
  [2] Dogman (2012)
  [3] Dogman 2: the Wrath of The Litter (2014)
  [RETURN] for default, [s]kip, [q]uit
   > Your Choice? 1

```

**Comment by jkwill87** [comment]
Sorry, mnamer v1 is no longer maintained. This is resolved in mnamer v2, please update if possible.

![image](https://user-images.githubusercontent.com/4343678/82517859-0f6d4480-9aec-11ea-82c2-0af57a45a7c4.png)

**Comment by colemar** [comment]
Well, [pip3 install --user mnamer] installed mnamer v1.4.2
How can I update to v2?

**Comment by jkwill87** [comment]
Update your version of python >= 3.6 then run `pip3 install --user --upgrade mnamer`. Support for Python 3.5 [will be end-on-life in the next couple of months](https://devguide.python.org/#status-of-python-branches) so it might be a good idea to update it in general anyway.

**Comment by colemar** [comment]
Upgraded, thank you.
