### ISSUE TITLE
KeyError: 'release_date'

### ISSUE THREAD

**Issue by colemar** [jkwill87/mnamer#87]
```
$ mnamer --version
mnamer v1.4.2

$ mnamer LAvventura.1960.mkv

Starting mnamer

Detected File
LAvventura.1960

Query Results
  [1] L'avventura (1960)
  [2] How Long Is the Adventure (1987)
  [3] Blonde in Black Leather (1975)
  [4] A Spasso Nel Tempo - L'avventura Continua (1997)
  [5] L'avventura Galante Di un Provinciale (1908)
Traceback (most recent call last):
  File "/usr/local/bin/mnamer", line 8, in <module>
    sys.exit(main())
  File "/home/admin/.local/lib/python3.5/site-packages/mnamer/__main__.py", line 385, in main
    process_files(targets, user_media, test_run, id_key, **config)
  File "/home/admin/.local/lib/python3.5/site-packages/mnamer/__main__.py", line 226, in process_files
    hit = next(results)
  File "/home/admin/.local/lib/python3.5/site-packages/mnamer/utils.py", line 235, in provider_search
    for result in provider_search.providers[media].search(id_key, **metadata):
  File "/home/admin/.local/lib/python3.5/site-packages/mapi/providers.py", line 115, in search
    for result in self._search_title(title, year):
  File "/home/admin/.local/lib/python3.5/site-packages/mapi/providers.py", line 160, in _search_title
    date=entry["release_date"],
KeyError: 'release_date'

```

**Comment by jkwill87** [comment]
As with #86 this is a bug with mnamer v1 which is no longer maintained. This also should be fixed in v2. Please upgrade if possible.

![image](https://user-images.githubusercontent.com/4343678/82517964-42173d00-9aec-11ea-9745-e5b25e410a56.png)
