### ISSUE TITLE
Crash Report

### ISSUE THREAD

**Issue by FunkeyMonkey** [jkwill87/mnamer#88]
Program is crashing if it tries to load from a config file. If i manually type it all out it works perfect. If i delete the config file and rerun the exact same line it goes through and movies the movie.
```
============================== CRASH REPORT BEGIN ==============================

--------------------------------- environment ----------------------------------

 - date = 2020-06-07
 - platform = Linux-4.19.115-v7l+-armv7l-with-debian-10.3
 - arguments = ['-r', '--no-guess', '--no-overwrite', '--movie-directory', '/media/pi/Storage/Download/', '--movie-format', '{name} ({year}){extension}', '/media/pi/Storage/Download/Test/']
 - python version = 3.7.3
 - mnamer version = 2.3.5
 - requests cache = /home/pi/.cache/mnamer-py3.7.sql

--------------------------------- stack trace ----------------------------------

Traceback (most recent call last):
  File "/home/pi/.local/lib/python3.7/site-packages/mnamer/__main__.py", line 32, in main
    run()
  File "/home/pi/.local/lib/python3.7/site-packages/mnamer/__main__.py", line 44, in run
    load_configuration=load_configuration, load_arguments=load_arguments
  File "<string>", line 36, in __init__
  File "/home/pi/.local/lib/python3.7/site-packages/mnamer/settings.py", line 337, in __post_init__
    self._load_configuration(configuration_path)
  File "/home/pi/.local/lib/python3.7/site-packages/mnamer/settings.py", line 425, in _load_configuration
    data = json.loads(file_pointer.read())
  File "/usr/lib/python3.7/json/__init__.py", line 348, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.7/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.7/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 25 column 24 (char 533)

=============================== CRASH REPORT END ===============================
```

**Comment by jkwill87** [comment]
> If i manually type it all out it works perfect

Do you mean if you use CLI arguments instead of a config file? If thats the case just pass whatever cli commands work for you along with `--config-dump` and that will output a valid config file with the arguments you provided.

Python is raising a `JSONDecodeError` so your current config file seems to be invalid JSON. If you paste the contents of your config file here I would be happy to give it a look.

**Comment by FunkeyMonkey** [comment]
Yes, if i use the CLI without a config file it goes through. I did save config command to create one and then just edit it to add the movie directory. Here's what i was using
```
"api_key_omdb": null,
    "api_key_tmdb": null,
    "api_key_tvdb": null,
    "api_key_tvmaze": null,
    "batch": false,
    "episode_api": "tvmaze",
    "episode_directory": null,
    "episode_format": "{series} - S{season:02}E{episode:02} - {title}{extension}",
    "hits": 5,
    "ignore": [
        ".*sample.*",
        "^RARBG.*"
    ],
    "lower": false,
    "mask": [
        ".avi",
        ".m4v",
        ".mp4",
        ".mkv",
        ".ts",
        ".wmv"
    ],
    "movie_api": "omdb",
    "movie_directory": /media/pi/Storage/VideosDVD/,
    "movie_format": "{name} ({year}){extension}",
    "no_cache": false,
    "no_guess": true,
    "no_overwrite": true,
    "no_style": false,
    "recurse": true,
    "replace_after": {
        "&": "and",
        ";": ",",
        "@": "at"
    },
    "replace_before": {},
    "scene": false,
    "verbose": false
}
```

**Comment by FunkeyMonkey** [comment]
So i did my manual cli and dumped the config and see the directory and format have " around them from when i was typing it, tried that in my config and all seems well now.
